### PR TITLE
Fifth Version

### PR DESCRIPTION
**Pull request by Aliceeeee2023**
姓名：Aliceeeee
網址：http://54.65.162.207:3000/
http://54.65.162.207:3000/attraction/1

上次的版本會新增`document.body.insertBefore(main, footer)`是因為當時還沒固定 footer ，所以寫了這段程式但忘了刪除，本次已經刪除。
然後有一起修改了首頁的 RWD 設定，從固定寬度更改為以百分比為主，謝謝老師～

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Second separating line should be 1px height with light grey color, just like top one.
2. http://54.65.162.207:3000/attraction/4 should have 4 images, but your image slider show only 3. Number of circles should depend on number of images.

**Comment by Aliceeeee2023** [comment]
已更改完成，再麻煩老師(ㆆᴗㆆ)
這次輪播圖完全在算數學，半夜算到頭都暈了XD（雖然很好玩）

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by Aliceeeee2023** [comment]
已重新選擇 reviewer，謝謝老師！

**Pull request merged**
